### ISSUE TITLE
`boltons.funcutils.wraps` breaks with Python 3 function annotations

### ISSUE THREAD

**Issue by rowillia** [mahmoud/boltons#133]
Tested with `boltons==17.1.0`

Repro: Executing the following script fails
```python
from boltons.funcutils import wraps
from typing import Optional

def wrap_it(f):
    @wraps(f)
    def wrapper(self, *args, **kwargs):
        f(*args, **kwargs)
    return wrapper

@wrap_it
def foo(x: Optional[int]) -> Optional[int]:
    return x
```

Results in
```bash
rwilliams at rwilliams-mbp114 in ~/src/oss/boltons (master●) (venv)
$ python ../../test_wraps_with_annotations.py
Traceback (most recent call last):
  File "../../test_wraps_with_annotations.py", line 11, in <module>
    def foo(x: Optional[int]) -> Optional[int]:
  File "../../test_wraps_with_annotations.py", line 5, in wrap_it
    @wraps(f)
  File "/Users/rwilliams/src/oss/boltons/boltons/funcutils.py", line 307, in wrapper_wrapper
    fully_wrapped = fb.get_func(execdict, with_dict=update_dict)
  File "/Users/rwilliams/src/oss/boltons/boltons/funcutils.py", line 526, in get_func
    self._compile(src, execdict)
  File "/Users/rwilliams/src/oss/boltons/boltons/funcutils.py", line 590, in _compile
    exec(code, execdict)
  File "<boltons.funcutils.FunctionBuilder-0>", line 1, in <module>
NameError: name 'Union' is not defined
```

**Comment by mahmoud** [comment]
Ah, using the fancy stuff! Good to see! Historically @markrwilliams oversees the Python 3 version of this, and I think it's supposed to support these features. Any quick ideas Mark?

**Comment by rowillia** [comment]
@mahmoud @markrwilliams This is what I came up with: https://github.com/mahmoud/boltons/pull/134 .  I know it's kind of gross, but it respects the letter of PEP 484 and I'm not familiar enough with boltons to know how to properly solve it.

**Comment by episodeyang** [comment]
Looks like I forgot to check the open issues! #138 

I'm running into similar issue.

```error
Traceback (most recent call last):
  File "/Users/ge/machine_learning/meta_learning_project/MAML_tensorflow/maml_bradly.py", line 273, in <module>
    def demo_fn(params: Some):
  File "/Users/ge/anaconda/envs/simulation/lib/python3.6/site-packages/moleskin/moleskin.py", line 31, in timeit
    @wraps(fn)
  File "/Users/ge/anaconda/envs/simulation/lib/python3.6/site-packages/boltons/funcutils.py", line 307, in wrapper_wrapper
    fully_wrapped = fb.get_func(execdict, with_dict=update_dict)
  File "/Users/ge/anaconda/envs/simulation/lib/python3.6/site-packages/boltons/funcutils.py", line 526, in get_func
    self._compile(src, execdict)
  File "/Users/ge/anaconda/envs/simulation/lib/python3.6/site-packages/boltons/funcutils.py", line 582, in _compile
    exec(code, execdict)
  File "<boltons.funcutils.FunctionBuilder-0>", line 1, in <module>
NameError: name '__main__' is not defined
```

**Comment by itamarst** [comment]
This is impacting one of my users: https://github.com/itamarst/eliot/issues/362

Anything I can do to get this fixed?

**Comment by mahmoud** [comment]
@itamarst Yes! If you have a reproducing case, check out #134.  I was waiting for a commit from Roy, but it never came. I most recently suspected that like `__doc__`, `__annotations__` can simply be copies from the old function to new. Could be a pretty quick fix!
