### ISSUE TITLE
`LRU` fails after `max_size` insertions

### ISSUE THREAD

**Issue by duerrp** [mahmoud/boltons#21]
Hi,
here's an example:
```
from boltons.cacheutils import LRU
cache = LRU(max_size = 2)
for i in xrange(4):
    cache[i] = i
    print(cache)
```
```
LRU(max_size=None, on_miss=2, values={0: 0})
LRU(max_size=None, on_miss=2, values={0: 0, 1: 1})
LRU(max_size=None, on_miss=2, values={1: 1, 2: 2})
Traceback (most recent call last):
  File "test_lru.py", line 9, in <module>
    cache[i] = i
  File "/usr/local/lib/python2.7/dist-packages/boltons/cacheutils.py", line 140, in __setitem__
    del self.link_map[oldkey]
KeyError: None
```

**Comment by mahmoud** [comment]
Looks like one line had escaped transcription! Thank you!
