### ISSUE TITLE
Sentinels are not picklable

### ISSUE THREAD

**Issue by mathrick** [mahmoud/boltons#285]
Since `make_sentinel` uses a local class defined within the function body, sentinels are not picklable, and as a consequence, `glom` can't easily be used with `muliprocessing`:

```python
Traceback (most recent call last):
  File "bin/testclient.py", line 200, in <module>
    main()
  File "bin/testclient.py", line 123, in main
    pool.map(task.run, get_mongo_batches()),
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'make_sentinel.<locals>.Sentinel'
```

**Comment by mahmoud** [comment]
Thanks for spotting this. There was certainly an attempt to make Sentinels pickleable at one point, but I think the version I'd copied in had assumptions that didn't hold true in a library setting. As in, the Sentinel type was created in some central module. I think I've got an approach now that works, will release shortly.
