### ISSUE TITLE
Python 3.10 `ecoutils` error: module `pprint` has no attribute `_safe_repr`

### ISSUE THREAD

**Issue by kdeldycke** [mahmoud/boltons#294]
I just stumble upon an issue with `ecoutils`. On Python 3.10 (which was just released today), I get the following error:

```python-tb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/work/meta-package-manager/meta-package-manager/meta_package_manager/__init__.py", line 22, in <module>
    from boltons.ecoutils import get_profile
  File "/home/runner/.cache/pypoetry/virtualenvs/meta-package-manager-r0mh58YI-py3.10/lib/python3.10/site-packages/boltons/ecoutils.py", line 357, in <module>
    _real_safe_repr = pprint._safe_repr
AttributeError: module 'pprint' has no attribute '_safe_repr'. Did you mean: 'saferepr'?
```

Source: https://github.com/kdeldycke/meta-package-manager/runs/3802697005?check_suite_focus=true#step:33:27

**Comment by kdeldycke** [comment]
Thanks @mahmoud for the quick fix! I'll use the tip of the main branch until the next release then! 😎👍
