### ISSUE TITLE
ParsedException.from_string produces wrong result when a frame is missing source (such as from eval)

### ISSUE THREAD

**Issue by asottile** [mahmoud/boltons#30]
Take this (modified from the original) trace:

```
Traceback (most recent call last):
  File "<string>", line 2, in _some_function
  File "myfile.py", line 3, in some_other_function
    return foo(bar, baz)
MyException: ExceptionValue
```

ParsedException gives me an incorrect result:

```
>>> ParsedException.from_string(x)
ParsedException(u'    return foo(bar, baz)', u'', frames=[{'source_line': u'File "myfile.py", line 3, in some_other_function', 'filepath': u'<string>', 'lineno': u'2', 'funcname': u'_some_function'}])
```

**Comment by asottile** [comment]
I should add, here's an easy way to generate a trace like this:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    h()
  File "test.py", line 8, in h
    eval('f()')
  File "<string>", line 1, in <module>
  File "test.py", line 2, in f
    g()
  File "test.py", line 5, in g
    raise TypeError('foo')
TypeError: foo
$ cat test.py
def f():
    g()

def g():
    raise TypeError('foo')

def h():
    eval('f()')

h()
```
