### ISSUE TITLE
23.1.1: pytest (8.1.0) fail

### ISSUE THREAD

**Issue by kloczek** [mahmoud/boltons#364]
Looks like pytest (8.1.0) fail
<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-boltons-23.1.1-5.fc36.x86_64/usr/lib64/python3.9/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-boltons-23.1.1-5.fc36.x86_64/usr/lib/python3.9/site-packages
+ /usr/bin/pytest -ra -m 'not network'
Traceback (most recent call last):
  File "/usr/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 195, in console_main
    code = main()
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 153, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 335, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1141, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1490, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1394, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/usr/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/warnings.py", line 150, in pytest_load_initial_conftests
    return (yield)
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.9/site-packages/_pytest/capture.py", line 153, in pytest_load_initial_conftests
    yield
  File "/usr/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1219, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 577, in _set_initial_conftests
    self._try_load_conftest(
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 625, in _try_load_conftest
    self._loadconftestmodules(
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 655, in _loadconftestmodules
    mod = self._importconftest(
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 731, in _importconftest
    self.consider_conftest(mod, registration_name=conftestpath_plugin_name)
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 812, in consider_conftest
    self.register(conftestmodule, name=registration_name)
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 497, in register
    plugin_name = super().register(plugin, name)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 167, in register
    self._verify_hook(hook, hookimpl)
  File "/usr/lib/python3.9/site-packages/pluggy/_manager.py", line 342, in _verify_hook
    raise PluginValidationError(
pluggy._manager.PluginValidationError: Plugin '/home/tkloczko/rpmbuild/BUILD/boltons-23.1.1/tests/conftest.py' for hook 'pytest_ignore_collect'
hookimpl definition: pytest_ignore_collect(path, config)
Argument(s) {'path'} are declared in the hookimpl but can not be found in the hookspec
```
</details>

**Comment by mahmoud** [comment]
Ah, good to know, I see a pytest [issue on this](https://github.com/pytest-dev/pytest/issues/11779), but it looks like it might require some updating. For now, boltons uses `pytest==7.2.0` as specified in the [requirements-test.txt](https://github.com/mahmoud/boltons/blob/8191b0ff3c56f1389a860f0c5124611c53c7f595/requirements-test.txt#L2). Thank you for the heads up!

**Comment by kloczek** [comment]
Just tested 24.0.0 and now all looks clean
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-boltons-24.0.0-2.fc36.x86_64/usr/lib64/python3.9/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-boltons-24.0.0-2.fc36.x86_64/usr/lib/python3.9/site-packages
+ /usr/bin/pytest -ra -m 'not network'
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.9.18, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/tkloczko/rpmbuild/BUILD/boltons-24.0.0
configfile: pytest.ini
plugins: mock-3.14.0
collected 416 items

tests/test_cacheutils.py ..................                                                                                                                                           [  4%]
tests/test_debugutils_trace.py ......                                                                                                                                                 [  5%]
tests/test_dictutils.py ...........................                                                                                                                                   [ 12%]
tests/test_ecoutils.py ..                                                                                                                                                             [ 12%]
tests/test_fileutils.py .                                                                                                                                                             [ 12%]
tests/test_formatutils.py .....                                                                                                                                                       [ 14%]
tests/test_funcutils.py .....                                                                                                                                                         [ 15%]
tests/test_funcutils_fb.py ...............                                                                                                                                            [ 18%]
tests/test_funcutils_fb_py3.py ......................                                                                                                                                 [ 24%]
tests/test_gcutils.py ..                                                                                                                                                              [ 24%]
tests/test_ioutils.py ..................................................................................                                                                              [ 44%]
tests/test_iterutils.py ........................................                                                                                                                      [ 54%]
tests/test_jsonutils.py ..                                                                                                                                                            [ 54%]
tests/test_listutils.py ..                                                                                                                                                            [ 55%]
tests/test_mathutils.py ...........                                                                                                                                                   [ 57%]
tests/test_namedutils.py ...                                                                                                                                                          [ 58%]
tests/test_queueutils.py ..                                                                                                                                                           [ 58%]
tests/test_setutils.py .....                                                                                                                                                          [ 60%]
tests/test_socketutils.py ...........                                                                                                                                                 [ 62%]
tests/test_statsutils.py .                                                                                                                                                            [ 62%]
tests/test_statsutils_histogram.py ..                                                                                                                                                 [ 63%]
tests/test_strutils.py ..............                                                                                                                                                 [ 66%]
tests/test_tableutils.py ...                                                                                                                                                          [ 67%]
tests/test_tbutils.py ..                                                                                                                                                              [ 68%]
tests/test_tbutils_parsed_exc.py ...                                                                                                                                                  [ 68%]
tests/test_timeutils.py ....                                                                                                                                                          [ 69%]
tests/test_typeutils.py ..                                                                                                                                                            [ 70%]
tests/test_urlutils.py ............................................................................................................................                                   [100%]

==================================================================================== 416 passed in 2.90s ====================================================================================
```

Thank you 👍 
Closing,

**Comment by mahmoud** [comment]
Thanks for being so fast and diligent!
