### ISSUE TITLE
`LRU` thread safety fails after `max_size` insertions

### ISSUE THREAD

**Issue by msambarino** [mahmoud/boltons#52]
Hi, i've come across an error when using `LRU` in a multi-threaded app, heres an example:

```python
from boltons.cacheutils import LRU
import threading
import time

cache = LRU(max_size = 2)

def fill_cache():
    for i in xrange(5):
        cache[i] = i
        print(cache)
        time.sleep(0.1)

t1 = threading.Thread(target=fill_cache)
t2 = threading.Thread(target=fill_cache)

t1.start()
t2.start()

t1.join()
t2.join()
```
```python
LRU(max_size=2, on_miss=None, values={0: 0})
LRU(max_size=2, on_miss=None, values={0: 0})
LRU(max_size=2, on_miss=None, values={0: 0, 1: 1})
LRU(max_size=2, on_miss=None, values={1: 1})
LRU(max_size=2, on_miss=None, values={1: 1, 2: 2})
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "lrutest.py", line 9, in fill_cache
    cache[i] = i
  File "/Users/mauri/.virtualenvs/lrutest/lib/python2.7/site-packages/boltons/cacheutils.py", line 149, in __setitem__
    del self.link_map[oldkey]
KeyError: 0

LRU(max_size=2, on_miss=None, values={2: 2, 3: 3})
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "lrutest.py", line 9, in fill_cache
    cache[i] = i
  File "/Users/mauri/.virtualenvs/lrutest/lib/python2.7/site-packages/boltons/cacheutils.py", line 149, in __setitem__
    del self.link_map[oldkey]
KeyError: 1
```
In case it helps, im using python **2.7.10** and boltons **15.1.0**

ps: Thanks for an awesome library!

**Comment by mahmoud** [comment]
You're very welcome! This does look like an issue, I'm looking into it now. Not sure if I'll have the fix tonight, but just wanted to drop a note saying, "confirmed." :+1:

**Comment by msambarino** [comment]
Great! thanks.

**Comment by mahmoud** [comment]
OK the problem has been found and a fix is on its way courtesy @markrwilliams so keep an eye out!

**Comment by markrwilliams** [comment]
it turns out this wasn't exactly a threading bug.  instead, there was an issue handling duplicate keys.

i took this as an opportunity to revisit the linked list code and move it into its own methods.  along the way i also improved locking (so we don't end up with an actual threading bug) and added some tests to improve confidence in the refactor.  

@msambarino i did test this PR against your excellent reproducing case (thanks for that!) and the bug did not occur.  i encourage you to test it yourself if you get a chance.

**Comment by mahmoud** [comment]
This looks up to spec, so I'm merging, thanks all!

**Comment by msambarino** [comment]
@markrwilliams This seems to have fixed my issue, many thanks to both of you!
